# Generated by Django 3.1 on 2020-08-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CluedoGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало игры')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='Окончание игры')),
                ('secret', models.TextField(max_length=1023, verbose_name='Загадка игры (кто, место, орудие)')),
                ('distances', models.TextField(max_length=1023, verbose_name='Расстояния между помещениями')),
            ],
        ),

        migrations.AddField(
            model_name='cluedogame',
            name='accusing',
            field=models.BooleanField(default=False, verbose_name='Обвинение'),
        ),
        migrations.AddField(
            model_name='cluedogame',
            name='alive',
            field=models.IntegerField(default=-1, verbose_name='осталось игроков'),
        ),
        migrations.AddField(
            model_name='cluedogame',
            name='asked',
            field=models.BooleanField(default=False, verbose_name='Вопрос задан'),
        ),
        migrations.AddField(
            model_name='cluedogame',
            name='asking',
            field=models.BooleanField(default=False, verbose_name='Вопрос задается'),
        ),
        migrations.AddField(
            model_name='cluedogame',
            name='choose_place',
            field=models.BooleanField(default=False, verbose_name='выбор места'),
        ),
        migrations.AddField(
            model_name='cluedogame',
            name='open_cards',
            field=models.TextField(blank=True, max_length=1023, null=True, verbose_name='Открытые в процессе игры карты в формате {"<type>": id}, где type = person, place, weapon'),
        ),
        migrations.AddField(
            model_name='cluedogame',
            name='started',
            field=models.BooleanField(default=False, verbose_name='игра началась'),
        ),
        migrations.AddField(
            model_name='cluedogame',
            name='turn_number',
            field=models.IntegerField(default=-1, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cluedogame',
            name='won',
            field=models.BooleanField(default=False, verbose_name=' Победа в игре'),
        ),
        migrations.AlterField(
            model_name='cluedogame',
            name='distances',
            field=models.TextField(blank=True, max_length=1023, null=True, verbose_name='Расстояния между помещениями'),
        ),
        migrations.AlterField(
            model_name='cluedogame',
            name='secret',
            field=models.TextField(blank=True, max_length=1023, null=True, verbose_name='Загадка игры (кто, место, орудие) в формате {"person": id, "place": id, "weapon": id}'),
        ),

        migrations.CreateModel(
            name='CluedoRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Название комнаты')),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.cluedogame', verbose_name='Игра в комнате')),
            ],
        ),

        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('telegram_id', models.CharField(max_length=255, null=True, verbose_name='id пользователя в Telegram')),
                ('state', models.CharField(max_length=255, verbose_name='Статус')),
                ('substate', models.IntegerField(null=True, verbose_name='Подстатус')),
                ('chat_id', models.IntegerField(null=True, verbose_name='Чат')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.cluedoroom', verbose_name='Комната')),
                ('last_message_id', models.CharField(max_length=64, blank=True, null=True, verbose_name='ID последнего сообщения пользователя в Telegram')),
            
            ],
        ),

        migrations.CreateModel(
            name='LinkedMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255, null=True)),
                # ('actions', models.TextField(max_length=4095, null=True)),
            ],
        ),

        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text_content', models.TextField(null=True)),
                ('media_name', models.CharField(max_length=255, null=True)),
                ('group', models.CharField(max_length=255, null=True)),
                ('order', models.IntegerField(null=True)),
                ('actions', models.TextField(null=True)),
            ],
        ),

        migrations.CreateModel(
            name='CluedoWeapon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Орудие убийства')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cluedoroom', verbose_name='Комната')),
            ],
        ),
        migrations.CreateModel(
            name='CluedoPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Место преступления')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cluedoroom', verbose_name='Комната')),
            ],
        ),
        migrations.CreateModel(
            name='CluedoPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Имя персонажа')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cluedoroom', verbose_name='Комната')),
            ],
        ),

        migrations.CreateModel(
            name='CluedoPlayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alive', models.BooleanField(default=True, verbose_name='игрок жив')),
                ('number', models.IntegerField(default=-1, verbose_name='номер игрока в порядке хода')),
                ('known_cards', models.TextField(blank=True, max_length=1023, null=True, verbose_name='Известные игроку карты')),
                ('cards', models.TextField(blank=True, max_length=1023, null=True, verbose_name='карты игрока')),
                ('alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.cluedoperson', verbose_name='игровой псевдоним игрока')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.cluedogame', verbose_name='ссылка на игру')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.cluedoplace', verbose_name='место, в котором находится игрок')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.user', verbose_name='Пользователь, который является игроком')),
            ],
        ),
    ]
