# Generated by Django 3.1 on 2020-08-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('telegram_id', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('substate', models.IntegerField(null=True)),
                ('chat_id', models.IntegerField(null=True)),
            ],
        ),

        migrations.CreateModel(
            name='LinkedMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255, null=True)),
                ('actions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text_content', models.TextField()),
                ('media_name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255, null=True)),
                ('order', models.IntegerField(null=True)),
                ('actions', models.TextField()),
            ],
        ),
        
    ]
