# Generated by Django 4.0.2 on 2022-04-13 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CluedoRooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Название комнаты')),
            ],
        ),
        migrations.AlterField(
            model_name='linkedmessages',
            name='actions',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='actions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CluedoWeapon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Орудие убийства')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cluedorooms', verbose_name='Комната')),
            ],
        ),
        migrations.CreateModel(
            name='CluedoPlaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Место преступления')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cluedorooms', verbose_name='Комната')),
            ],
        ),
        migrations.CreateModel(
            name='CluedoPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Имя персонажа')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cluedorooms', verbose_name='Комната')),
            ],
        ),
    ]
