telegram:
  token:
  webhook_host: https://cluedo-bot.herokuapp.com
  webhook_path: /
  webhook_port: 443
  webhook_cert:
  webhook_key:
server:
  host: 0.0.0.0
  port: 8000
  log_file: ./bot.log
django: 
  secret:
  allowed_hosts:
    - 127.0.0.1
